<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace GPBMetadata;

class Product
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aad020a0d70726f647563742e70726f746f120770726f6475637422080a" .
            "06566163616e7422310a0b50726f647563744c69737412220a0870726f64" .
            "7563747318012003280b32102e70726f647563742e50726f647563742217" .
            "0a0950726f647563744964120a0a02696418012001280522320a0750726f" .
            "64756374120a0a026964180120012805120c0a046e616d65180220012809" .
            "120d0a0570726963651803200128093280010a0e50726f64756374536572" .
            "7669636512370a0c6c69737450726f6475637473120f2e70726f64756374" .
            "2e566163616e741a142e70726f647563742e50726f647563744c69737422" .
            "0012350a0b7265616450726f6475637412122e70726f647563742e50726f" .
            "6475637449641a102e70726f647563742e50726f64756374220062067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

