<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Product;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>product.ProductList</code>
 */
class ProductList extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .product.Product products = 1;</code>
     */
    private $products;

    public function __construct() {
        \GPBMetadata\Product::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .product.Product products = 1;</code>
     */
    public function getProducts()
    {
        return $this->products;
    }

    /**
     * <code>repeated .product.Product products = 1;</code>
     */
    public function setProducts(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Product\Product::class);
        $this->products = $var;
    }

}

