<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: product.proto

namespace Product;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>product.Vacant</code>
 */
class Vacant extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Product::initOnce();
        parent::__construct();
    }

}

